In [4]:
import pandas as pd #pandas for managing the data.
import plotly.express as px #plotly.express for visualizing the data.
import datetime
import json #json for reading json file formats.

In [5]:
#Let's read the data into pandas dataframe and look at the first 5 rows using the head() method.

In [6]:
gasoline = pd.read_csv("Data/18100001.csv")
gasoline.head()

,REF_DATE,GEO,DGUID,Type of fuel,UOM,UOM_ID,SCALAR_FACTOR,SCALAR_ID,VECTOR,COORDINATE,VALUE,STATUS,SYMBOL,TERMINATED,DECIMALS
0,Jan-79,"St. John's, Newfoundland and Labrador",2011S0503001,Regular unleaded gasoline at full service fill...,Cents per litre,57,units,0,v735046,2.1,26.0,NaN,NaN,t,1
1,Jan-79,"Charlottetown and Summerside, Prince Edward Is...",NaN,Regular unleaded gasoline at full service fill...,Cents per litre,57,units,0,v735056,3.1,24.6,NaN,NaN,t,1
2,Jan-79,"Halifax, Nova Scotia",2011S0503205,Regular unleaded gasoline at full service fill...,Cents per litre,57,units,0,v735057,4.1,23.4,NaN,NaN,t,1
3,Jan-79,"Saint John, New Brunswick",2011S0503310,Regular unleaded gasoline at full service fill...,Cents per litre,57,units,0,v735058,5.1,23.2,NaN,NaN,t,1
4,Jan-79,"Québec, Quebec",2011S0503421,Regular unleaded gasoline at full service fill...,Cents per litre,57,units,0,v735059,6.1,22.6,NaN,NaN,t,1

In [7]:
#Let's find out how many entries there are in our dataset, using shape function.
gasoline.shape

(41942, 15)

In [8]:
#Using info function, we will take a look at our types of data.
gasoline.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41942 entries, 0 to 41941
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   REF_DATE       41942 non-null  object
 1   GEO            41942 non-null  object
 2   DGUID          39451 non-null  object
 3   Type of fuel   41942 non-null  object
 4   UOM            41942 non-null  object
 5   UOM_ID         41942 non-null  int64
 6   SCALAR_FACTOR  41942 non-null  object
 7   SCALAR_ID      41942 non-null  int64
 8   VECTOR         41942 non-null  object
 9   COORDINATE     41942 non-null  float64
 10  VALUE          41942 non-null  float64
 11  STATUS         0 non-null      float64
 12  SYMBOL         0 non-null      float64
 13  TERMINATED     16564 non-null  object
 14  DECIMALS       41942 non-null  int64
dtypes: float64(4), int64(3), object(8)
memory usage: 4.8+ MB

In [9]:
#Using columns method, we will print all the column names.
gasoline.columns

Index(['REF_DATE', 'GEO', 'DGUID', 'Type of fuel', 'UOM', 'UOM_ID',
       'SCALAR_FACTOR', 'SCALAR_ID', 'VECTOR', 'COORDINATE', 'VALUE', 'STATUS',
       'SYMBOL', 'TERMINATED', 'DECIMALS'],
      dtype='object')

In [10]:
#we will check for any missing values.
gasoline.isnull().sum()

REF_DATE             0
GEO                  0
DGUID             2491
Type of fuel         0
UOM                  0
UOM_ID               0
SCALAR_FACTOR        0
SCALAR_ID            0
VECTOR               0
COORDINATE           0
VALUE                0
STATUS           41942
SYMBOL           41942
TERMINATED       25378
DECIMALS             0
dtype: int64

In [11]:
#Below, we are filtering our data, by selecting only the relevant columns. Also, we are using the rename() method to change the name of the columns.
#Selecting and renaming the columns of interest

data = (gasoline[['REF_DATE','GEO','Type of fuel','VALUE']]).rename(columns={"REF_DATE" : "DATE", "Type of fuel" : "TYPE"})
data.head()

,DATE,GEO,TYPE,VALUE
0,Jan-79,"St. John's, Newfoundland and Labrador",Regular unleaded gasoline at full service fill...,26.0
1,Jan-79,"Charlottetown and Summerside, Prince Edward Is...",Regular unleaded gasoline at full service fill...,24.6
2,Jan-79,"Halifax, Nova Scotia",Regular unleaded gasoline at full service fill...,23.4
3,Jan-79,"Saint John, New Brunswick",Regular unleaded gasoline at full service fill...,23.2
4,Jan-79,"Québec, Quebec",Regular unleaded gasoline at full service fill...,22.6

In [27]:
#Splitting the columns
#The str.split() function splits the string records, by a 'comma', with n=1 slplit, and 
#Expend=True , returns a dataframe.
#Below, we are splitting 'GEO' into 'City' and 'Province'.

In [28]:
data[['City', 'Province']] = data['GEO'].str.split(',', n=1, expand=True)
data.head()

,DATE,GEO,TYPE,VALUE,Month,Year,City,Province
0,1979-01-01,"St. John's, Newfoundland and Labrador",Regular unleaded gasoline at full service fill...,26.0,Jan,1979,St. John's,Newfoundland and Labrador
1,1979-01-01,"Charlottetown and Summerside, Prince Edward Is...",Regular unleaded gasoline at full service fill...,24.6,Jan,1979,Charlottetown and Summerside,Prince Edward Island
2,1979-01-01,"Halifax, Nova Scotia",Regular unleaded gasoline at full service fill...,23.4,Jan,1979,Halifax,Nova Scotia
3,1979-01-01,"Saint John, New Brunswick",Regular unleaded gasoline at full service fill...,23.2,Jan,1979,Saint John,New Brunswick
4,1979-01-01,"Québec, Quebec",Regular unleaded gasoline at full service fill...,22.6,Jan,1979,Québec,Quebec

In [12]:
#Changing to datetime format
#If we scroll up to our gasoline.info() section, we can find that 'REF_DATE' is an object type.
#To be able to filter by day, month, or year, we need to change the format from object type to datetime.
#Pandas function to_datetime() transforms to date time format. Also, we need to specify the format of
#datetime that we need. In our case, format='%b-%y' means that it will split into the name of a month
#and year. str.slice(stop=3) splits and outputs the first 3 letters of a month

In [13]:
data['DATE'] = pd.to_datetime(data['DATE'], format='%b-%y')
data['Month'] = data['DATE'].dt.month_name().str.slice(stop=3)
data['Year'] = data['DATE'].dt.year

In [14]:
data.head()

,DATE,GEO,TYPE,VALUE,Month,Year
0,1979-01-01,"St. John's, Newfoundland and Labrador",Regular unleaded gasoline at full service fill...,26.0,Jan,1979
1,1979-01-01,"Charlottetown and Summerside, Prince Edward Is...",Regular unleaded gasoline at full service fill...,24.6,Jan,1979
2,1979-01-01,"Halifax, Nova Scotia",Regular unleaded gasoline at full service fill...,23.4,Jan,1979
3,1979-01-01,"Saint John, New Brunswick",Regular unleaded gasoline at full service fill...,23.2,Jan,1979
4,1979-01-01,"Québec, Quebec",Regular unleaded gasoline at full service fill...,22.6,Jan,1979

In [15]:
#The describe() function provides statistical information about the numeric variables.
#Since we only have the 'VALUE' variable that we want statistical information on, we will filter 
#it by data.VALUE.describe() function.

In [16]:
data.VALUE.describe() # or data['VALUE'].describe()

count    41942.000000
mean        84.784858
std         31.492697
min         18.300000
25%         58.200000
50%         79.200000
75%        110.900000
max        191.600000
Name: VALUE, dtype: float64

In [17]:
#it is useful to know what is inside our categorical variables. 
#We will use unique().tolist() functions to print out all of our 'GEO' colunm
data.GEO.unique().tolist() # or data['GEO'].unique().tolist()

["St. John's, Newfoundland and Labrador",
 'Charlottetown and Summerside, Prince Edward Island',
 'Halifax, Nova Scotia',
 'Saint John, New Brunswick',
 'Québec, Quebec',
 'Montréal, Quebec',
 'Ottawa-Gatineau, Ontario part, Ontario/Quebec',
 'Toronto, Ontario',
 'Thunder Bay, Ontario',
 'Winnipeg, Manitoba',
 'Regina, Saskatchewan',
 'Saskatoon, Saskatchewan',
 'Edmonton, Alberta',
 'Calgary, Alberta',
 'Vancouver, British Columbia',
 'Victoria, British Columbia',
 'Whitehorse, Yukon',
 'Yellowknife, Northwest Territories']

In [18]:
#print out all categories in 'TYPE' column
data.TYPE.unique().tolist()

['Regular unleaded gasoline at full service filling stations',
 'Regular unleaded gasoline at self service filling stations',
 'Premium unleaded gasoline at full service filling stations',
 'Premium unleaded gasoline at self service filling stations',
 'Diesel fuel at full service filling stations',
 'Household heating fuel',
 'Diesel fuel at self service filling stations']

In [19]:
#Data Filtering

In [20]:
#Filtering with logical operators
#We can use the logical operators on column values to filter rows. First, we specify the name of our
#data, then, square brackets to select the name of the column, double 'equal' sign, '==' to select the
#name of a row group, in single or double quotation marks. If we want to exclude some entries 
#(e.g. some locations), we would use the 'equal' and 'exclamation point' signs together, '=!'.
#We can also use '</>', '<=/>=' signs to select numeric information.
#Let's select the Calgary, Alberta data to see all the information.

In [21]:
calgary = data[data['GEO'] == 'calgary, Alberta']
calgary

Empty DataFrame
Columns: [DATE, GEO, TYPE, VALUE, Month, Year]
Index: []

In [22]:
#Now, let's select 2000 year.
sel_years = data[data['Year'] == 2000]
sel_years

,DATE,GEO,TYPE,VALUE,Month,Year
16168,2000-01-01,"St. John's, Newfoundland and Labrador",Regular unleaded gasoline at full service fill...,78.0,Jan,2000
16169,2000-01-01,"St. John's, Newfoundland and Labrador",Regular unleaded gasoline at self service fill...,74.9,Jan,2000
16170,2000-01-01,"St. John's, Newfoundland and Labrador",Premium unleaded gasoline at full service fill...,84.5,Jan,2000
16171,2000-01-01,"St. John's, Newfoundland and Labrador",Premium unleaded gasoline at self service fill...,81.3,Jan,2000
16172,2000-01-01,"St. John's, Newfoundland and Labrador",Diesel fuel at full service filling stations,69.2,Jan,2000
...,...,...,...,...,...,...
17579,2000-12-01,"Yellowknife, Northwest Territories",Premium unleaded gasoline at full service fill...,92.6,Dec,2000
17580,2000-12-01,"Yellowknife, Northwest Territories",Premium unleaded gasoline at self service fill...,95.4,Dec,2000
17581,2000-12-01,"Yellowknife, Northwest Territories",Diesel fuel at full service filling stations,81.9,Dec,2000
17582,2000-12-01,"Yellowknife, Northwest Territories",Diesel fuel at self service filling stations,78.9,Dec,2000
17583,2000-12-01,"Yellowknife, Northwest Territories",Household heating fuel,58.8,Dec,2000

In [23]:
#Filtering by multiple conditions
#There are many alternative ways to perform filtering in pandas.
#We can also use '|' ('or') and '&' (and) to select multiple columns and rows.
#For example, let us select Toronto and Edmonton locations.

In [24]:
mult_loc = data[(data['GEO'] == "Toronto, Ontario") | (data['GEO'] == "Edmonton, Alberta")]
mult_loc

,DATE,GEO,TYPE,VALUE,Month,Year
7,1979-01-01,"Toronto, Ontario",Regular unleaded gasoline at full service fill...,23.0,Jan,1979
12,1979-01-01,"Edmonton, Alberta",Regular unleaded gasoline at full service fill...,18.3,Jan,1979
22,1979-02-01,"Toronto, Ontario",Regular unleaded gasoline at full service fill...,23.2,Feb,1979
27,1979-02-01,"Edmonton, Alberta",Regular unleaded gasoline at full service fill...,18.5,Feb,1979
37,1979-03-01,"Toronto, Ontario",Regular unleaded gasoline at full service fill...,23.2,Mar,1979
...,...,...,...,...,...,...
41903,2021-10-01,"Toronto, Ontario",Diesel fuel at self service filling stations,141.3,Oct,2021
41904,2021-10-01,"Toronto, Ontario",Household heating fuel,148.0,Oct,2021
41920,2021-10-01,"Edmonton, Alberta",Regular unleaded gasoline at self service fill...,138.3,Oct,2021
41921,2021-10-01,"Edmonton, Alberta",Premium unleaded gasoline at self service fill...,159.6,Oct,2021
41922,2021-10-01,"Edmonton, Alberta",Diesel fuel at self service filling stations,134.7,Oct,2021

In [29]:
#Alternatively, we can use isin method to select multiple locations.
cities = ['Calgary', 'Toronto', 'Edmonton']
CTE = data[data.City.isin(cities)]
CTE

,DATE,GEO,TYPE,VALUE,Month,Year,City,Province
7,1979-01-01,"Toronto, Ontario",Regular unleaded gasoline at full service fill...,23.0,Jan,1979,Toronto,Ontario
12,1979-01-01,"Edmonton, Alberta",Regular unleaded gasoline at full service fill...,18.3,Jan,1979,Edmonton,Alberta
13,1979-01-01,"Calgary, Alberta",Regular unleaded gasoline at full service fill...,18.7,Jan,1979,Calgary,Alberta
22,1979-02-01,"Toronto, Ontario",Regular unleaded gasoline at full service fill...,23.2,Feb,1979,Toronto,Ontario
27,1979-02-01,"Edmonton, Alberta",Regular unleaded gasoline at full service fill...,18.5,Feb,1979,Edmonton,Alberta
...,...,...,...,...,...,...,...,...
41921,2021-10-01,"Edmonton, Alberta",Premium unleaded gasoline at self service fill...,159.6,Oct,2021,Edmonton,Alberta
41922,2021-10-01,"Edmonton, Alberta",Diesel fuel at self service filling stations,134.7,Oct,2021,Edmonton,Alberta
41923,2021-10-01,"Calgary, Alberta",Regular unleaded gasoline at self service fill...,140.8,Oct,2021,Calgary,Alberta
41924,2021-10-01,"Calgary, Alberta",Premium unleaded gasoline at self service fill...,164.4,Oct,2021,Calgary,Alberta
41925,2021-10-01,"Calgary, Alberta",Diesel fuel at self service filling stations,138.3,Oct,2021,Calgary,Alberta

In [31]:
#selecting the data that shows the price of the 'household heating fuel', in Vancouver, in 1990.
temp_data = data[(data['Year']== 1990 ) & (data['TYPE'] == "Household heating fuel") & (data['City'] =='Vanciuver' )]
temp_data

Empty DataFrame
Columns: [DATE, GEO, TYPE, VALUE, Month, Year, City, Province]
Index: []

In [32]:
#Filtering using groupby() method
#The role of groupby() is to analyze data by some categories. The simplest call is by a column name.
#For example, let’s use the 'GEO' Column and ngroups function to calculate the number of 
#groups (cities, provinces) in 'GEO' colum

In [37]:
geo = data.groupby('GEO')
geo.ngroups

18

In [38]:
#Most commonly, we use groupby() to split the data into groups,this will apply some function to 
#each of the groups (e.g. mean, median, min, max, count), then combine the results into a data structure.
#For example, let's select the 'VALUE' column and calculate the mean of the gasoline prices per year.
#First, we specify the 'Year" column, following by the 'VALUE' column, and the mean() function.

In [39]:
group_year = data.groupby(['Year'])['VALUE'].mean()
group_year

Year
1979     23.604444
1980     28.068750
1981     38.002604
1982     44.701563
1983     47.904688
1984     50.442708
1985     53.899479
1986     48.405208
1987     49.758333
1988     49.217188
1989     51.700000
1990     55.048735
1991     56.527041
1992     54.633832
1993     54.334734
1994     54.247899
1995     56.177451
1996     58.134110
1997     59.182062
1998     56.247246
1999     58.743362
2000     72.207839
2001     72.403107
2002     70.312147
2003     75.541667
2004     82.960452
2005     96.328743
2006    101.209393
2007    105.258263
2008    123.340678
2009     96.969068
2010    106.369845
2011    126.790607
2012    130.380085
2013    129.677273
2014    133.169203
2015    110.366908
2016    101.790821
2017    112.852657
2018    129.408575
2019    125.776329
2020    107.617150
2021    133.990580
Name: VALUE, dtype: float64

In [40]:
#using groupby() method to group by the maximum value of gasoline prices, for each month.

In [42]:
temp1_data = data.groupby(['Year', 'City'])['VALUE'].median()

In [43]:
temp1_data

Year  City
1979  Calgary                          19.15
      Charlottetown and Summerside     25.45
      Edmonton                         18.70
      Halifax                          24.00
      Montréal                         23.25
                                       ...
2021  Vancouver                       151.10
      Victoria                        148.80
      Whitehorse                      142.25
      Winnipeg                        127.70
      Yellowknife                     138.65
Name: VALUE, Length: 751, dtype: float64